// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oesuzvcxmglxkuvpjrke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lc3V6dmN4bWdseGt1dnBqcmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODcyNjMsImV4cCI6MjA3MDY2MzI2M30.XSEdwXhvQQUyS7q7bHeu5FOk1N7cqvBlU9Nk2o9mlSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});